dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install docker==4.1.0 pytest

services:
  - docker

env:
  - NAME='latest' BUILD_PATH='python3.7' TEST_STR1='Hello world! From Uvicorn with Gunicorn. Using Python 3.7' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.7'
  - NAME='python3.8' BUILD_PATH='python3.8' TEST_STR1='Hello world! From Uvicorn with Gunicorn. Using Python 3.8' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.8'
  - NAME='python3.7' BUILD_PATH='python3.7' TEST_STR1='Hello world! From Uvicorn with Gunicorn. Using Python 3.7' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.7'
  - NAME='python3.6' BUILD_PATH='python3.6' TEST_STR1='Hello world! From Uvicorn with Gunicorn. Using Python 3.6' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.6'
  - NAME='python3.8-alpine3.10' BUILD_PATH='python3.8-alpine3.10' TEST_STR1='Hello world! From Uvicorn with Gunicorn in Alpine. Using Python 3.8' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.8'
  - NAME='python3.7-alpine3.8' BUILD_PATH='python3.7-alpine3.8' TEST_STR1='Hello world! From Uvicorn with Gunicorn in Alpine. Using Python 3.7' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.7'
  - NAME='python3.6-alpine3.8' BUILD_PATH='python3.6-alpine3.8' TEST_STR1='Hello world! From Uvicorn with Gunicorn in Alpine. Using Python 3.6' TEST_STR2='Test app. From Uvicorn with Gunicorn. Using Python 3.6'
  

script:
  - bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
